tokyo_region           = "ap-northeast-1"
tokyo_bucket_name      = "rpc-monitoring-lambda-tokyo"
tokyo_lambda_name      = "rpc-monitoring-lambda-tokyo"
tokyo_lambda_s3_bucket = "rpc-monitoring-lambda-tokyo"
tokyo_lambda_layer_arn = "arn:aws:lambda:ap-northeast-1:764866452798:layer:chrome-aws-lambda:26"
tokyo_event_rule_name  = "invoke-rpc-monitor-tokyo-every-5-minutes"